"""Versioned operational assumptions, not clinical or epidemiological estimates."""
CONFIG_VERSION = "resilience-v1"
HORIZON = 14
MAX_SCENARIOS = 20
DENGUE = {"moderate": .20, "severe": .50, "critical": .90}
DELAY_DAYS = {"moderate": 3, "severe": 7, "critical": 14}
STAFF_UNAVAILABLE = {"moderate": .20, "severe": .40, "critical": .65}
CAPACITY_REDUCTION = {"moderate": .25, "severe": .50, "critical": 1.0}
ABNORMAL_STD = 3
ESCALATION_DOMAINS = 2
PRIORITY_PATIENT_SCALE = 10000
FEVER_ADMISSION_RATE = .10
SERVICE_HEADROOM = 1.25
DEFAULT_DISCHARGE_RATE = .20
LOW_COVER_DAYS = 7
CRITICAL_DAYS = 3
RISK_WATCH = .20
RISK_WARNING = .50
RISK_CRITICAL = .80
OCCUPANCY_WATCH = .85
OCCUPANCY_WARNING = .95
STAFF_WATCH = .85
STAFF_WARNING = .70
STAFF_CRITICAL = .50
WORKLOAD_WARNING = 1.0
WORKLOAD_CRITICAL = 1.4
SURGE_WATCH = .15
SURGE_WARNING = .35
SURGE_CRITICAL = .70
SEVERITY_RANK = {"INFO": 0, "WATCH": 1, "WARNING": 2, "CRITICAL": 3}
PRIORITY_WEIGHTS = {"severity": 100, "urgency": 20, "probability": 20, "patients": 10, "hospital": 5}
